---
name: Template-Plugin-ListMoreUtils
version: 0.02
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
abstract: TT2 plugin to use List::MoreUtils
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  List::MoreUtils: 0.22
  Template: 2.20
  Template::Plugin::VMethods: 0.02
configure_requires:
  Module::Build: 0.34
provides:
  Template::Plugin::ListMoreUtils:
    file: lib/Template/Plugin/ListMoreUtils.pm
    version: 0.02
  Template::Plugin::ListMoreUtilsVMethods:
    file: lib/Template/Plugin/ListMoreUtilsVMethods.pm
    version: 0.02
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
